apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvd-rental
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: poopy-test
          image: jeacott/postgres-demo-s6
          imagePullPolicy: "IfNotPresent"
          # ports:
          #     - containerPort: 5432