apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvd-rental-app
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: python-pod
          image: jeacott/dvdrental:v1.3
          ports:
            # This is the port we'll expose to the internet eventually
            - name: web
              containerPort: 8888
---
