apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvd-rental
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: postgres-pod
          image: jeacott/postgres-demo-s6:v1.0
          imagePullPolicy: "IfNotPresent"